### ISSUE TITLE
Django's update_or_create doesnt work with automatic routing

### ISSUE THREAD

**Issue by 4word** [JBKahn/django-sharding#34]
I will open a PR for this, we noticed it while porting over some functionality from our non-sharded environment to our pre-production system.

**Comment by JBKahn** [comment]
If you can open a PR with a broken test I can take a look.

**Comment by 4word** [comment]
I actually already fixed it and just need to back port it to master when I have a chance. Will open up the PR later today.

**Comment by 4word** [comment]
I actually already fixed it and just need to back port it to master when I have a chance. Will open up the PR later today.

**Comment by JBKahn** [comment]
Ditto for this.
