### ISSUE TITLE
exists() doesnt work with automatically routed querysets

### ISSUE THREAD

**Issue by 4word** [JBKahn/django-sharding#35]
I am not sure why this is broken, but for some reason the way django's klone() method on the queryset works, the hints dont get copied over for the router to use. I have to investigate, will open a PR when I have a fix.

**Comment by 4word** [comment]
Also, I assumed it worked similarly to count(), which DOES work, but no, it doesnt for some reason. Makes no sense to me -_-

**Comment by JBKahn** [comment]
Ditto, If you can open a PR with broken tests I can take a look as well.

**Comment by 4word** [comment]
Ok I will open one up later today / this evening

**Comment by 4word** [comment]
So the unit test in our infrastructure at my work is now passing with no problems lol, not sure why exists() wasnt working for us. I have a feeling the guy writing those tests did something obviously wrong, reported the bug to me, and then fixed it without thinking about it. I think this is safe to close since you have some good unit tests in your branch.

**Comment by JBKahn** [comment]
Alright, I'll close this for now and we can re-open it if there are edge cases.
