### ISSUE TITLE
Travis unit tests strangeness

### ISSUE THREAD

**Issue by 4word** [JBKahn/django-sharding#44]
Looking at the travis.yml file vs the runtests.py file, it appears that in the travis file, mysql is setup as shard001 and postgres as shard002, but in the settings section of runtests.py, it appears to be reversed. Am I just seeing things? Is that intentional?

**Comment by JBKahn** [comment]
the inconsistency was never used as travis populates the correct env vars. Fixed in https://github.com/JBKahn/django-sharding/pull/42
