### ISSUE TITLE
CI tests invariantly running on python 3.5

### ISSUE THREAD

**Issue by hockeybuggy** [JBKahn/django-sharding#49]
Not sure what the cause is yet, but it seems that tests are running on python 3.5 in every build on travis.

e.g.
From build [168155582](https://travis-ci.org/JBKahn/django-sharding/jobs/168155582) py27-dj18

```
$ python --version
Python 3.5.2
```

and py35-dj18

```
$ python --version
Python 3.5.2
```

**Comment by JBKahn** [comment]
how sure are you? line 172 which comes after that is what should be settings the version used during tests iirc:
```
 tox -e $TOX_ENV
```

**Comment by hockeybuggy** [comment]
Ah you're right. So the "system python" in all of the builds are and the venvs use different pythons.

From the `cat .tox/$TOX_ENV/log/*.log` call at the end:

```
cmdargs: ['/home/travis/virtualenv/python3.5.2/bin/python', '-m', 'virtualenv', '--python', '/opt/python/2.7.9/bin/python2.7', 'py27-dj18']
```

Thanks @JBKahn . Nothing to see here.

**Comment by JBKahn** [comment]
np, thanks for investigating and reporting it. Much appreciated.
