### ISSUE TITLE
Migrating from 2.* to 5.*

### ISSUE THREAD

**Issue by M1hacka** [JBKahn/django-sharding#89]
Hi.
Is there a list of incompatibilities between 2.x and latest major versions somewhere?
I get error after updating to the latest (5.1.0) version:
```
@model_config(shard_group='shards_group', sharded_by_field='test_related_model')
TypeError: model_config() got an unexpected keyword argument 'sharded_by_field'
```
There is no any information about such a release in github, 3.0.0 release doesn't contain any usefull information

UPD: Looks like this error started from version 5.0.0

**Comment by JBKahn** [comment]
https://github.com/JBKahn/django-sharding/blob/master/CHANGES.md I think is what you're looking for

**Comment by M1hacka** [comment]
Thanks
